# Esto es REST Client, para probar la API REST cuando no tienes el frontend. Se puede usar Yaak, Postman, etc.

### login
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Registro de nuevo usuario con role
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "admin",
  "email": "bori@example.com",
  "password": "admin123",
  "role": "front office Manager"
}

### Borrar usuario por ID
DELETE http://localhost:3000/users/da708205-6549-11f0-9104-d8bbc147dfea

Authorization: Bearer TOKEN AQUI

### Obtener todos los usuarios (solo si estás autenticado como manager)
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkdlbmVyYWwgTWFuYWdlciIsImlhdCI6MTc1MzQwMTE1NiwiZXhwIjoxNzUzNDI5OTU2fQ.sclWqNMMyM0lALz7K3FkpMWtJN-Ry5s0RFYmz9RwU0U

