# Esto es REST Client, para probar la API REST cuando no tienes el frontend. Se puede usar Yaak, Postman, etc.

### login
POST http://localhost:3000/login

### Registro de nuevo usuario con role
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "bori3",
  "email": "bori@example.com",
  "password": "securepassword123",
  "role": "front office Manager"
}

### Borrar usuario por ID
## Tengo que borrar 
## '96f53d82-6446-11f0-8664-309c239384ce', 'bori2', 'bori@example.com'
## '7f402725-6444-11f0-8664-309c239384ce', 'bori', 'bori@example.com'
## '8edf030f-6447-11f0-8664-309c239384ce', bori3, 'bori@example.com'
DELETE http://localhost:3000/users/56b47bf2-6446-11f0-8664-309c239384ce